//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.08.16 at 04:37:32 PM IST 
//


package com.saurabh.courses;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="CourseDataDetails" type="{http://saurabh.com/courses}CourseDataDetails"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "courseDataDetails"
})
@XmlRootElement(name = "AddNewCourseDetailsRequest")
public class AddNewCourseDetailsRequest {

    @XmlElement(name = "CourseDataDetails", required = true)
    protected CourseDataDetails courseDataDetails;

    /**
     * Gets the value of the courseDataDetails property.
     * 
     * @return
     *     possible object is
     *     {@link CourseDataDetails }
     *     
     */
    public CourseDataDetails getCourseDataDetails() {
        return courseDataDetails;
    }

    /**
     * Sets the value of the courseDataDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link CourseDataDetails }
     *     
     */
    public void setCourseDataDetails(CourseDataDetails value) {
        this.courseDataDetails = value;
    }

}
